env:
  es6: true
  browser: true
  webextensions: true
extends: 'eslint:recommended'
parser: babel-eslint
parserOptions:
  ecmaVersion: 8
  sourceType: module
rules:
  no-console: 0
  'no-unused-vars': 'off'
globals:
  DEBUG: true
  PRODUCTION: true
  ga: true
